# Generated by Django 3.2.7 on 2021-09-30 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Brand Name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Brand Visibility')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(help_text='Title', max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, help_text='Product Description', verbose_name='Description')),
                ('image', models.ImageField(default='images/600_900.png', help_text='Select Image', upload_to='images/', verbose_name='Image')),
                ('buying_price', models.PositiveIntegerField(default=0, verbose_name='Buying Price')),
                ('regular_price', models.PositiveBigIntegerField(default=0, verbose_name='Regular Price')),
                ('sale_price', models.PositiveBigIntegerField(default=0, help_text='Price On Sale', verbose_name='Discounted Price')),
                ('quantity', models.IntegerField(default=1, help_text='Stock', verbose_name='Quantity')),
                ('wieght', models.DecimalField(decimal_places=2, default=0, help_text='Weight in Gram', max_digits=6, verbose_name='Product Weight')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Stock Availability')),
                ('is_active', models.BooleanField(default=True, verbose_name='Product Visibility')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='store.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='store.category')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
